### ISSUE TITLE
[Issue]: Cant add mending to items with unbreaking on them

### ISSUE THREAD

**Issue by NunbearTWITCH** [The-Nexus-Project/Limitless-7#69] opened 2024-01-11 12:05 UTC
### What happened?

Whenever a player on the server tries to add mending to an item with unbreaking it crashes them to desktop

### Pack Version

Version: 0.35.1

### To Reproduce

1.use an item with unbreaking in an anvil and try to add mending

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by BigAngelUK** [comment] 2024-01-11 12:22
[crash-2024-01-11_11.48.06-client.txt](https://github.com/The-Nexus-Project/Limitless-7/files/13903077/crash-2024-01-11_11.48.06-client.txt)

**Comment by Aydenss** [comment] 2024-01-12 08:23
The crash happens very often with lots of enchantment

**Comment by Gbergz** [comment] 2024-01-12 08:46
While I can't reproduce this myself I'll investigate more either way.

**Comment by Aydenss** [comment] 2024-01-12 11:23
I send a attachment an example of a crash when I try to apply Mending on a Refined Obsidian paxel which has enchantments incompatible with Mending

[crash-2024-01-12_12.21.00-client.txt](https://github.com/The-Nexus-Project/Limitless-7/files/13918404/crash-2024-01-12_12.21.00-client.txt)

**Comment by Gbergz** [comment] 2024-01-12 11:39
Oh it's that specific crash, it's reported to Universal Enchants, hopefully fixed in the future.

**Comment by Gbergz** [comment] 2024-01-18 12:36
Fixed in 0.36.0 mod removed for the time being, sorry if you used it. But issue is reported to the mod author.

**Closed by Gbergz** 2024-01-18 12:36 UTC
Labels: issue
