### ISSUE TITLE
[Issue]: AE2 Wireless Booster Uses Uncraftable Ender Pearl Dust

### ISSUE THREAD

**Issue by Incompatibility** [The-Nexus-Project/Limitless-7#27] opened 2023-10-05 16:20 UTC
### What happened?

 AE2 Wireless Booster Uses Uncraftable Ender Pearl Dust that has a cancel symbol on it.

the tag in question is "forge:dusts/ender_pearl"

### Pack Version

Version: 0.25.0

### To Reproduce

1. Search for the wireless booster recipe in EMI

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Incompatibility** [comment] 2023-10-05 16:22
So it actually is craftable, but with normally unobtainable "barrier" blocks

**Comment by Gbergz** [comment] 2023-10-05 16:53
Screenshot

**Comment by Incompatibility** [comment] 2023-10-05 17:27
![image](https://github.com/The-Nexus-Project/Limitless-7/assets/15383630/135285b7-73f9-412e-a331-2578d44f44ae)
![image](https://github.com/The-Nexus-Project/Limitless-7/assets/15383630/742c23af-51a1-4f36-90a8-5e88415b6283)
![image](https://github.com/The-Nexus-Project/Limitless-7/assets/15383630/f69d22e7-1869-4c2e-8761-88a9e02217d8)

**Comment by Incompatibility** [comment] 2023-10-05 17:28
![image](https://github.com/The-Nexus-Project/Limitless-7/assets/15383630/ae05993d-5617-4e4e-86c4-549c21ed4340)

**Comment by Gbergz** [comment] 2023-10-05 17:52
Can't reproduce this issue, have you tried reinstalling the modpack?

Also before doing that, try making a new world then reenter your current one.

**Comment by Gbergz** [comment] 2023-10-10 11:52
This will be fixed in the upcoming update.

**Closed by Gbergz** 2023-10-10 11:52 UTC
Labels: issue
