### ISSUE TITLE
[Issue]: Textures Dont Load all is Black

### ISSUE THREAD

**Issue by Altiger99** [The-Nexus-Project/Limitless-7#7] opened 2023-08-29 12:37 UTC
### What happened?

Wehen i start the game and join the server all textures are Black. 

### Pack Version

Version: Newest Version

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment] 2023-08-29 12:40
Reinstall the modpack, update drivers. Most likely not a modpack specific issue but rather a driver/pc specific issue.

**Comment by TaskMaster115** [comment] 2023-09-03 02:53
hello, I'm having the same issue, I've done everything mentioned before and none of it works so if anyone can help it would be very appreciated.

**Comment by x0tempus0x** [comment] 2023-09-03 09:28
Same here. Drivers are up to date, windows10 up to date. Tried it with and without shaders and a resourcepack. 3 other 1.20.1 modpack played/tested and they work. Sorry to say it, but it has to be the modpack.

**Comment by Gbergz** [comment] 2023-09-03 09:30
Probably not the modpack, no it's such a small % of players that seem to get this. 
And I for the love of god can't reproduce it. Tried my best.

Sorry for the issues.

**Comment by Fl5mmi** [comment] 2023-09-03 12:33
I personally have it only with the new version 0.20.0. I updated from the version 0.19.1 to the newest but with black textures exept Creatures and chests (don´t know if it´s important). I Started update regulary since 0.15.0 and never had any problems with bugs until the newest version. I´m using Oculus. Drivers and oculus are the newest version.

**Comment by Gbergz** [comment] 2023-09-03 12:37
If you're using Oculus, that is most likely why. 

It's not in the pack by default and pack isn't really developed with it in mind. Report issues to Oculus.

**Comment by Sinakast** [comment] 2023-09-03 17:05
I am having the same issue.  Black textures for the world, Quest list icons are black, player inventory and chest inventory icons are black.  Entities such as cows and bees render though.  I don't use any resource packs or shaders, I uninstalled and reinstalled twice, I even switched my vanilla minecraft launcher to 1.20.1 to see if that helped, and nothing worked.

![TNP blackout loot chest](https://github.com/The-Nexus-Project/Limitless-7/assets/143957410/3d02a242-f3a7-4919-8968-78d2fda9bc1d)

**Comment by Gbergz** [comment] 2023-09-03 17:07
For other people reading this issue: 
I can't fix or attempt to fix an issue that isn't reproducable for me myself. Sorry. But I will investigate either way.

**Comment by Sinakast** [comment] 2023-09-03 17:37
> For other people reading this issue: I can't fix or attempt to fix an issue that isn't reproducable for me myself. Sorry. But I will investigate either way.

Yep, just giving what additional info I can to facilitate a (hopefully) fix.  TNP is the go-to modpack for me to play with my kids, I hate to lose it.

**Comment by Gbergz** [comment] 2023-09-03 17:39
Do you have an AMD gpu?

**Comment by TaskMaster115** [comment] 2023-09-03 17:53
I have AMD gpu

**Comment by Gbergz** [comment] 2023-09-03 17:55
Yeah we've narrowed it down to being an AMD gpu specific issue.

**Comment by Sinakast** [comment] 2023-09-03 18:29
I don't see anything AMD when I run dxdiag.  Not sure exactly what I am looking for, but the 'chip type' under display is NVIDIA GeForce GTX 745.

**Comment by Gbergz** [comment] 2023-09-03 19:01
Need testing, remove Chisels and bits and see if it works again.

**Comment by x0tempus0x** [comment] 2023-09-03 19:10
Tested. Disabling Chisel&Bits does nothing, sorry.

**Comment by Gbergz** [comment] 2023-09-03 19:48
Don't use oculus if you do.

**Comment by Gbergz** [comment] 2023-09-03 23:24
Fixed in v0.20.1

**Closed by Gbergz** 2023-09-03 23:24 UTC
Labels: issue, not reproducable

**Comment by TaskMaster115** [comment] 2023-09-04 06:46
thank you very much for the quick fix love your guys' work

**Comment by x0tempus0x** [comment] 2023-09-04 15:01
sadly I've still got black textures....

**Comment by x0tempus0x** [comment] 2023-09-04 15:37
Mhmm, but would be nice to know what exactly IS the problem, because as already mentioned, I played 5 other 1.20.1 modpacks (fabric and forge) and all of them work.

**Comment by Gbergz** [comment] 2023-09-04 15:39
I've been at this for 24+hours now. (debugging) It's hard to know. And I can't debug it myself since Nvidia works without any issues.

Have to have others that have AMD help me. This will take time. And no, you can't compare modpacks.

**Comment by x0tempus0x** [comment] 2023-09-04 16:11
I know, I know, and you do a great work with your modpacks. It was more a question to me, than to you.  Maybe its a mod, maybe its an option in the AMD software or both interact somehow.... who knows.

**Comment by Sinakast** [comment] 2023-09-04 23:38
> I know, I know, and you do a great work with your modpacks. It was more a question to me, than to you. Maybe its a mod, maybe its an option in the AMD software or both interact somehow.... who knows.

Did you try deleting your profile and making sure you only have TNP 0.20.1?  I had to delete my 0.20.0 profile and do a fresh download of 0.20.1.  My textures were fixed with 0.20.1 (I had the blackout issue with NVIDIA, not AMD), but the quests were broken until I deleted everything and started over.

**Comment by Celi-161** [comment] 2023-09-06 11:34
I just updated to the 1.20.1 version and the textures are also still black (except chests & mobs). This problem occured firstly in 1.19.0 but I was able to fix it by updating drivers and taking out ressource packs i've added. Now nothing seems to be working to fix it myself. (AMD Radeon RX570 GPU)

**Comment by Gbergz** [comment] 2023-09-06 12:41
This issue will probably be a long standing one until probably one day it just disappears. Sorry folk. No AMD card here so can't do the thorough testing I want to do.

**Comment by x0tempus0x** [comment] 2023-09-07 14:40
Magic was done over night ;-)  Mr. Berg, u little demon, what did you do? As I told you yesterday, I installed the modpack to another PC and it worked.

Today I thought, maybe there is an update and damn why not, I installed the modpack again on my main pc.... and et voila, textures visible :)  So I'm testing/playing it for a while and then try to install oculus and shaders.

**Comment by Gbergz** [comment] 2023-09-07 14:56
@x0tempus0x From last hotfix that supposedly fixed it (apparently didn't) I haven't done anything more. 
But I am glad it's working for some reason again.

**Comment by x0tempus0x** [comment] 2023-09-08 20:01
like Amy Winehouse sang... I go back to black. After updating to 0.21 texture are vanishing again. :(

**Comment by Gbergz** [comment] 2023-09-08 20:02
This issue will probably be a long standing one until probably one day it just disappears. Sorry folks. No AMD card here so can't do the thorough testing I want to do.

**Comment by ky7333** [comment] 2023-09-09 21:22
Did some tracing and think i found the culprit. It ultimately comes down to the texture size of the blocks.png-atlas which gets stitched together. OpenGL's GL_MAX_TEXTURE_SIZE for most GPUs is 16384, to my knowledge the only exception is RTX cards which report 32768. In v0.20.0 it tries to make a 32768x16384 texture which crashes, in v0.20.1with chisel and bits gone it drops down to 16384x16384 so it works on all modern GPUs and in v0.21.0 the additional mods make it jump back up to 32768x16384. I think with this high of a mod count theres not much that can be done unless the atlas can be split up. I did notice this line in v0.20.0 "Created: 256x256x0 chiselsandbits:textures/atlases/icons.png-atlas" so it seems some mods split parts out.

**Comment by TaskMaster115** [comment] 2023-09-10 06:46
hello im having the same issue but this time in the 0.21.0v anything i can do to maybe fix the issue?

**Comment by x0tempus0x** [comment] 2023-09-10 07:17
so with the answer from ky7333 I've looked through the mods and disabled 3 more. Stoneworks, rechiseled and rechiseledcreate because (i hope) these are only cosmetic mods. Looks like this saved enough textures and the world is not black :)

**Comment by Gbergz** [comment] 2023-09-10 08:55
Interesting that this is an issue in Minecraft 1.20.1 and not 1.19.2: somethings gotta have changed or it's just a bug with 1.20

**Comment by Gbergz** [comment] 2023-09-10 11:11
People having this issue, can you try updating PneumaticCraft to its latest version? It contains fixes for the Atlas texture thing.

That version specifically: (v6.0.5)
https://legacy.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized/files/4746442

**Comment by Gbergz** [comment] 2023-09-10 11:16
Related: `https://github.com/TeamPneumatic/pnc-repressurized/issues/1212`

**Comment by SilentiumDingo** [comment] 2023-09-10 16:04
I downloaded the pack had this issue and updated only PneumaticCraft to v6.0.5 and it fixed my issue

**Comment by Gbergz** [comment] 2023-09-10 16:06
Thanks for the tests, people and the replies. I apprecate this. I will release a hotfix with the PneumaticCraft update included later.. Or just v.0.22.0.

**Comment by jinkhya** [comment] 2023-09-10 16:07
I had someone on my server who has an AMD card and was experiencing the bug test this and he said with : 
- broken with pneumaticcraft-repressurized 6.0.4+mc1.20.1
- fixed with pneumaticcraft-repressurized 6.0.5+mc1.20.1

 :D

**Comment by jinkhya** [comment] 2023-09-10 16:08
lol I'm late to the party, oh well, happy that a fix was found <3

**Comment by fallintolife** [comment] 2023-09-11 01:13
Still black textures here. 
Pneumatic 6.0.5
AMD Radeon RX 5600 XT
AMD Adrenaline ver 23.9.1 (current version).

**Comment by REACTY99** [comment] 2023-09-11 09:52
The texture are still black even in the latest update 0.22.0 
i have a 6600XT and latest drivers

**Comment by Gbergz** [comment] 2023-09-11 09:54
🤷‍♂️

**Comment by x0tempus0x** [comment] 2023-09-11 14:54
Updating Pneumaticcraft did the job. All mods enabled and textures are visible. For all of you who still have black textures, mabe you want to try what I did. Disable cosmetic mods like I did. Stoneworks, rechiseled and rechiseledcreate. Seems like it saves a ton of textures. ( if thats how it works :) )

**Comment by Gbergz** [comment] 2023-09-11 14:56
Nah removing mods shouldn't really be needed to solve it, it's a mod causing it. PneumaticCraft should be the cause, seems fixed for most ppl after updating it. But apparently not all. 🤷‍♂️

**Comment by x0tempus0x** [comment] 2023-09-11 15:02
Mhmm, maybe its a problem with not enough GPU RAM? I have a RX 6900 XT with 16 GB so its enough for the textures?

**Comment by Gbergz** [comment] 2023-09-11 15:04
It's an OpenGL problem with the atlas texture getting too big apparently. It was reported by 6+ ppl who had the problem initially that updating PneumaticCraft solved it. 

PNC had stitched all their texture to it (atlas), but not in their newest update.

**Comment by x0tempus0x** [comment] 2023-09-11 15:32
S... happens. I also tried texture (resource) packs, but none of the couple I've tested worked. (testet 32x to 128x :) )

**Comment by Yamadaisme** [comment] 2023-09-12 20:17
![2023-09-12_16 13 54](https://github.com/The-Nexus-Project/Limitless-7/assets/92765169/3821d292-3306-4f33-8ca7-74fee0e7e138)
So this is a known problem. I thought this was my setting of embeddium.

**Comment by Gbergz** [comment] 2023-09-12 20:17
No, it's a bug. Known one, thanks for report again though...

**Comment by chezzyboy21** [comment] 2023-09-12 22:15
i tried updating the PneumaticCraft and its on its newest version, and its still complete darkness around the world, i do not have anything extra installed with it i just have the basic pack.

![image](https://github.com/The-Nexus-Project/Limitless-7/assets/90969744/c12224b1-e209-4467-8ce3-2853912e8b37)

**Comment by Gbergz** [comment] 2023-09-12 22:22
Thanks for the comment, but this is known. Closing comments for now.

**Comment by Gbergz** [comment] 2023-09-19 15:48
Issue might be resolved in latest update (v0.23.0), give it a try.

**Comment by jinkhya** [comment] 2023-09-19 22:21
Hello, just letting you know i had 2 people playing on my server trying 0.23 and it was fixed for them. Got 2 more to go but it's looking promising! :D 
Good job!

**Comment by Yamadaisme** [comment] 2023-09-20 15:15
There is no way to use shader for this modpack right? The game crashed when I add oculus in

**Comment by jinkhya** [comment] 2023-09-20 15:43
Oculus is not compatible with latest version of embeddium yet (embeddium replaced rubidium)

**Comment by Gbergz** [comment] 2023-09-21 22:48
Looks like it's finally solved then, let's hope it doesn't come back.
Closed.
